apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-deployment
  labels:
    app: logs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
      - name: logs
        image: logs-deployment:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: logs-service
spec:
  type: ClusterIP
  selector:
    app: logs
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000